#include <stdexcept>

int main() {
    throw std::runtime_error("I am a error!");
}
